In [7]:
import pandas as pd
import numpy as np

In [8]:
df1 = pd.read_csv('../data/Clean_DIM_TIENDA.csv')
df2 = pd.read_csv('../data/Clean_Ventas.csv')

In [9]:
df_merged = pd.merge(df1, df2, on="TIENDA_ID", how="inner")  
df_merged.head()

,TIENDA_ID,PLAZA_CVE,NIVELSOCIOECONOMICO_DES,ENTORNO_DES,MTS2VENTAS_NUM,PUERTASREFRIG_NUM,CAJONESESTACIONAMIENTO_NUM,LATITUD_NUM,LONGITUD_NUM,SEGMENTO_MAESTRO_DESC,LID_UBICACION_TIENDA,MES_ID,VENTA_TOTAL
0,126,1,BC,HOGAR,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202406,78331.04
1,126,1,BC,HOGAR,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202402,984454.29
2,126,1,BC,HOGAR,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202307,1096866.62
3,126,1,BC,HOGAR,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202310,775114.25
4,126,1,BC,HOGAR,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202304,1095804.32

In [10]:
umbrales = {
    "Base": 480000,
    "Hogar": 490000,
    "Peatonal": 420000,
    "Receso": 516000
}

# Asegurar que ENTORNO_DES no tenga espacios extras también
df_merged["ENTORNO_DES"] = df_merged["ENTORNO_DES"].str.strip().str.capitalize()  # estandariza

# Crear columna TARGET
df_merged["TARGET"] = df_merged.apply(
    lambda row: 1 if row["VENTA_TOTAL"] >= umbrales.get(row["ENTORNO_DES"], float('inf')) else 0,
    axis=1
)

In [11]:
df_merged.head()

,TIENDA_ID,PLAZA_CVE,NIVELSOCIOECONOMICO_DES,ENTORNO_DES,MTS2VENTAS_NUM,PUERTASREFRIG_NUM,CAJONESESTACIONAMIENTO_NUM,LATITUD_NUM,LONGITUD_NUM,SEGMENTO_MAESTRO_DESC,LID_UBICACION_TIENDA,MES_ID,VENTA_TOTAL,TARGET
0,126,1,BC,Hogar,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202406,78331.04,0
1,126,1,BC,Hogar,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202402,984454.29,1
2,126,1,BC,Hogar,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202307,1096866.62,1
3,126,1,BC,Hogar,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202310,775114.25,1
4,126,1,BC,Hogar,127.42,13,7,25.69107,-100.21261,HOGAR REUNIÓN,UT_DENSIDAD,202304,1095804.32,1